// oxlint-disable typescript/no-explicit-any

import type { StoryFn, ArgTypes } from '@storybook/react';

// Interfaces matching the custom control object structures generated by the functions
export type BaseControlResult = ArgTypes<{ x: number }>['x'];

export interface EnumControlResult extends Omit<BaseControlResult, 'control'> {
  options: string[];
  control: {
    type: 'radio' | 'check';
  };
}

export const createStringControl = (
  description: string,
  defaultValue: string
): BaseControlResult => {
  return {
    table: {
      type: { summary: 'string' },
      defaultValue: { summary: defaultValue }
    },
    description: description,
    control: { type: 'text' }
  };
};

export const createBooleanControl = (
  description: string,
  defaultValue: boolean
): BaseControlResult => {
  return {
    table: {
      type: { summary: 'boolean' },
      defaultValue: { summary: defaultValue as unknown as string }
    },
    description: description,
    control: { type: 'boolean' }
  };
};

export const createEnumControl = (
  description: string,
  defaultValue: string,
  values: (string | number | boolean | undefined)[]
): EnumControlResult => {
  return {
    table: {
      type: { summary: values.join('|') },
      defaultValue: { summary: defaultValue }
    },
    description: description,
    options: values as string[],
    control: { type: 'radio' }
  };
};

export const createNumberControl = (
  description: string,
  defaultValue: number,
  min?: number,
  max?: number,
  step?: number
): BaseControlResult => {
  return {
    table: {
      type: { summary: 'number' },
      defaultValue: { summary: defaultValue as unknown as string }
    },
    description: description,
    control: { type: 'number', min, max, step }
  };
};

export const createRangeControl = (
  description: string,
  defaultValue: number,
  min?: number,
  max?: number,
  step?: number
): BaseControlResult => {
  return {
    table: {
      type: { summary: 'range' },
      defaultValue: { summary: defaultValue as unknown as string }
    },
    description: description,
    control: { type: 'range', min, max, step }
  };
};

export const createMultiEnumControl = (
  description: string,
  defaultValue: string | string[],
  values: string[]
): EnumControlResult => {
  return {
    table: {
      type: { summary: values.join('|') },
      defaultValue: { summary: defaultValue }
    },
    description: description,
    options: values,
    control: { type: 'check' }
  };
};

/**
 * Mutates a Story object to add argTypes and dynamically extracts default 
 * values out of the custom configuration directly into the story's initial args.
 */
export function configureArgs<TArgs = any>(
  story: StoryFn<TArgs>,
  argTypes: ArgTypes<TArgs>
): void {
  story.argTypes = argTypes;
  story.args = Object.keys(argTypes).reduce<Record<string, any>>((acc, curr) => {
    acc[curr] = (argTypes as any)[curr].table.defaultValue.summary;
    return acc;
  }, {}) as TArgs;
};
